-- Age Kiosk logs table for Supabase
create table if not exists public.detection_logs (
  id bigint generated by default as identity primary key,
  timestamp text not null,
  mode text,
  raw_age double precision,
  final_status text,
  birth_date text,
  verified_age integer
);

create index if not exists idx_detection_logs_timestamp_desc
  on public.detection_logs (timestamp desc);

create index if not exists idx_detection_logs_final_status
  on public.detection_logs (final_status);

alter table public.detection_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'detection_logs'
      and policyname = 'detection_logs_select_all'
  ) then
    create policy detection_logs_select_all
      on public.detection_logs
      for select
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'detection_logs'
      and policyname = 'detection_logs_insert_all'
  ) then
    create policy detection_logs_insert_all
      on public.detection_logs
      for insert
      with check (true);
  end if;
end
$$;

